### ISSUE TITLE
Progress Tracker

### ISSUE THREAD

**Issue by Murali03M** [kunal-kushwaha/DSA-Bootcamp-Java#928]
# Progress Tracker

## DSA
- [x] Complete Git & GitHub Course
- [x] Introduction to Programming
  - - [x] Types of languages
  - - [x] Memory management
- [x] Flow of the program
  - - [x] Flowcharts 
  - - [x] Pseudocode
- [x] Introduction to Java
  - - [x] Introduction
  - - [x] How it works
  - - [x] Setup Installation
  - - [x] Input and Output in Java
  - - [x] Conditionals & Loops in Java
    - - [x] if else
    - - [x] loops
    - - [x] Switch statements
  - - [x] Data types
  - - [x] Coding best practices
- [x] Functions
  - - [x] Introduction
  - - [x] Scoping in Java
  - - [x] Shadowing 
  - - [x] Variable Length Arguments
  - - [x] Overloading
- [x] Arrays
  - - [x] Introduction 
  - - [x] Memory management 
  - - [x] Input and Output
  - - [x] ArrayList Introduction
  - - [x] Sorting 
    - - [x] Insertion Sort
    - - [x] Selection Sort
    - - [x] Bubble Sort
    - - [x] Cyclic Sort (Merge sort etc after recursion)
  - [x] Searching 
    - - [x] Linear Search
    - - [x] Binary Search
    - - [x] Modified Binary Search
    - - [x] Binary Search Interview questions
    - - [x] Binary Search on 2D Arrays
- [x] Pattern questions
- [x] Strings
    - [x] Introduction
    - [x] How Strings work
    - [x] Comparison of methods
    - [x] Operations in Strings
    - [x] StringBuilder in java
- [x] Maths for DSA
    - - [x] Introduction
    - - [x] Complete Bitwise Operators
    - - [x] Prime numbers
    - - [x] HCF / LCM
    - - [x] Sieve of Eratosthenes
    - - [x] Newton's Square Root Method
    - - [x] Number Theory
    - - [x] Euclidean algorithm
- [x] Space and Time Complexity Analysis
    - - [x] Introduction
    - - [x] Comparion of various cases
    - - [x] Solving Linear Recurrence Relations
    - - [x] Solving Divide and Conquer Recurrence Relations
    - - [x] Big-O, Big-Omega, Big-Theta Notations
    - - [x] Get equation of any relation easily - best and easiest approach
    - - [x] Complexity discussion of all the problems we do
    - - [x] Space Complexity 
    - - [x] Memory Allocation of various languages
    - - [x] NP Completeness and Hardness
- [x] Recursion
    - - [x] Introduction
    - - [x] Why recursion?
    - - [x] Flow of recursive programs - stacks
    - - [x] Convert recursion to iteration
    - - [x] Tree building of function calls
    - - [x] Tail recursion
    - - [x] Sorting:
        - - [x] Merge Sort
        - - [x] Quick Sort
    - - [x] Backtracking
        - - [x] Sudoku Solver
        - - [x] N-Queens
        - - [x] N-Knights
        - - [x] Maze problems
    - - [x] Recursion String Problems
    - - [x] Recursion Array Problems
    - - [x] Recursion Pattern Problems
    - - [x] Subset Questions
    - - [x] Recursion - Permutations, Dice Throws etc Questions
- [x] Object Oriented Programming
    - - [x] Introduction
    - - [x] Classes & its instances
    - - [x] this keyword in Java
    - - [x] Properties
        - - [x] Inheritance
        - - [x] Abstraction
        - - [x] Polymorphism
        - - [x] Encapsulation
    - - [x] Overloading & Overriding
    - - [x] Static & Non-Static
    - - [x] Access Control
    - - [x] Interfaces
    - - [x] Abstract Classes
    - - [x] Singleton Class
    - - [x] final, finalize, finally
    - - [x] Exception Handling
- [x] Linked List
    - - [x] Introduction
    - - [x] Singly and Doubly Linked List
    - - [x] Circular Linked List
    - - [x] Fast and slow pointer
    - - [x] Cycle Detection
    - - [x] Reversing of LinekdList
    - - [x] Linked List Interview questions
- [x] Stacks & Queues
    - - [x] Introduction
    - - [x] Interview problems
    - - [x] Push efficient
    - - [x] Pop efficient
    - - [x] Queue using Stack and Vice versa
    - - [x] Circular Queue
- [ ] Dynamic Programming
    - - [x] Introduction
    - - [x] Recursion + Recursion DP + Iteration + Iteration Space Optimized
    - - [x] Complexity Analysis
    - - [x] 0/1 Knapsack
    - - [x] Subset Questions
    - - [x] DP on Grids
    - - [x] LC Questions on Above topics
    - - [ ] Unbounded Knapsack
    - - [x] Subseq questions
    - - [ ] String DP
- [ ] Trees
    - - [x] Introduction
    - - [x] Binary Trees
    - - [x] Recursive Preorder, Inorder, Postorder Traversals
    - - [x] Iterative Preorder, Inorder, Postorder Traversals
    - - [x] LC Questions
    - - [x] DFS
    - - [x] BFS  
    - - [x] Morris Traversal `O(1) Space`
    - - [x] Binary Search Trees
    - - [x] LC Questions
    - - [ ] AVL Trees
    - - [ ] Segment Tree
    - - [ ] Fenwick Tree / Binary Indexed Tree
- [ ] Heaps
    - - [x] Introduction
    - - [x] Theory
    - - [x] Priority Queue
    - - [ ] Two Heaps Method
    - - [ ] k-way merge
    - - [ ] top k elements
    - - [ ] interval problems
- [ ] Hashmaps
    - - [x] Introduction
    - - [x] Theory - how it works
    - - [x] Comparisons of various forms
    - - [x] Limitations and how to solve
    - - [x] Map using LinkedList
    - - [x] Map using Hash
    - - [x] Chaining
    - - [x] Probing
    - - [ ] Huffman-Encoder
- [ ] Tries
    - - [x] Introduction
    - - [x] Theory - how it works
    - - [x] Applications
    - - [x] Insert and Search
    - - [ ] GFG articles and Questions
    - - [ ] Interview Questions
- [ ] Graphs
    - - [x] Introduction
    - - [x] BFS
    - - [x] DFS
    - - [x] Working with graph components
    - - [x] Bipartite Graph
    - - [x] LC Questions
    - - [ ] Minimum Spanning Trees
    - - [ ] Kruskal Algorithm
    - - [ ] Prims Algorithm
    - - [x] Dijkstra’s shortest path algorithm
    - - [x] Topological Sort
    - - [x] Kahn's Algorithm
    - - [ ] Bellman ford
    - - [ ] A* pathfinding Algorithm
- [ ] Greedy Algorithms
    - - [x] Introduction
    - - [x] Applications
    - - [x] LC,GFG Questions
    - - [ ] Interview Questions

### Advanced concepts apart from interviews 
- [ ] Fast IO
- [x] File handling
- [ ] Bitwise + DP
- [ ] Extended Euclidean algorithm
- [ ] Modulo Multiplicative Inverse
- [ ] Linear Diophantine Equations
- [ ] Matrix Exponentiation
- [ ] Mathematical Expectation
- [ ] Catalan Numbers
- [ ] Fermat’s Theorem
- [ ] Wilson's Theorem
- [ ] Euler's Theorem
- [x] Lucas Theorem
- [x] Chinese Remainder Theorem
- [ ] Euler Totient
- [ ] NP-Completeness
- [x] Multithreading
- [ ] Fenwick Tree / Binary Indexed Tree
- [ ] Square Root Decomposition

**Comment by Aman254** [comment]
Hey @Murali03M did you covered everything Including basic and advance all topics or something is still left
